services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB:-contextos}
      POSTGRES_USER: ${PG_USER:-contextos}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-contextos}
    volumes: [pgdata:/var/lib/postgresql/data]

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672","15672:15672"]


volumes:
  pgdata:
